const ESTADOS = [
  { abr: 'AC', nome: 'Acre' },
  { abr: 'AL', nome: 'Alagoas' },
  { abr: 'AP', nome: 'Amapá' },
  { abr: 'AM', nome: 'Amazonas' },
  { abr: 'BA', nome: 'Bahia' },
  { abr: 'CE', nome: 'Ceará' },
  { abr: 'DF', nome: 'Distrito Federal' },
  { abr: 'ES', nome: 'Espírito Santo' },
  { abr: 'GO', nome: 'Goiás' },
  { abr: 'MA', nome: 'Maranhão' },
  { abr: 'MT', nome: 'Mato Grosso' },
  { abr: 'MS', nome: 'Mato Grosso do Sul' },
  { abr: 'MG', nome: 'Minas Gerais' },
  { abr: 'PA', nome: 'Pará' },
  { abr: 'PB', nome: 'Paraíba' },
  { abr: 'PR', nome: 'Paraná' },
  { abr: 'PE', nome: 'Pernambuco' },
  { abr: 'PI', nome: 'Piauí' },
  { abr: 'RJ', nome: 'Rio de Janeiro' },
  { abr: 'RN', nome: 'Rio Grande do Norte' },
  { abr: 'RS', nome: 'Rio Grande do Sul' },
  { abr: 'RO', nome: 'Rondônia' },
  { abr: 'RR', nome: 'Roraima' },
  { abr: 'SC', nome: 'Santa Catarina' },
  { abr: 'SP', nome: 'São Paulo' },
  { abr: 'SE', nome: 'Sergipe' },
  { abr: 'TO', nome: 'Tocantins' },
];